### ISSUE TITLE
Insane requests to public ip's from HiveMQ (Public MQTT Broker)

### ISSUE THREAD

**Issue by nuclimedia** [probonopd/go-appimage#200] opened 2022-04-27 13:15 UTC
Accidentally I have detected connections to external ip's (3.123.180.179 and 52.59.17.149) from appimaged. They belong to an MQTT Broker.

```tcp        0     17 00.00.0.0:53010     3.123.180.179:1883      ESTABLISHED 6114/appimaged-649-
tcp        0     17 00.00.0.0:41860     52.59.17.149:1883       ESTABLISHED 6114/appimaged-649-
tcp        0      0 00.00.0.0:41864     52.59.17.149:1883       ESTABLISHED 6114/appimaged-649-
tcp        0     17 00.00.0.0:41868     52.59.17.149:1883       ESTABLISHED 6114/appimaged-649-
```

They seems to be legitimate connections from appimaged daemon. Maybe to perform autoupdate tasks. But in no case would the frequency (one per second) or the need to connect to external IPs be justified.

For me, this is an abuse of privacy and should be removed as soon as possible.

**Comment by probonopd** [comment] 2022-04-27 16:37
Thanks @nuclimedia. Seems to be a bug, duplicate of https://github.com/probonopd/go-appimage/issues/144.
Do you know how to fix it?

**Closed by probonopd** 2022-04-27 16:37 UTC
